Azure/azure-data-lake-store-python

adlfs/__init__.py
adlfs/cli.py
adlfs/core.py
adlfs/lib.py
adlfs/multithread.py
adlfs/utils.py

Instead of defining the logging handlers inside the library, we now defer logging to the user/application. This will make it easier to filter and redirect log messages.
I also added the ability to define the log level in the CLI, both as a convenience during development but also as an example of application-level logging.
While this doesn't fully address #47, this is a first pass.

PR: Standardize logging

---

adlfs/cli.py
adlfs/multithread.py

I ran multiple experiments to find the optimal settings for the downloader. 
For any number of threads, a 4MB chunk size is optimal, so I updated the default:
```
Download benchmarks (10GB remote, single file local)
Threads  Chunk Size  Elapsed    Rate
-------  ----------  ---------  ------------
4         4MB  224.3178s  45.6497 MB/s
8        32MB  251.6219s  40.6960 MB/s
8        16MB  237.1416s  43.1810 MB/s
8         8MB  225.4522s  45.4198 MB/s
8         4MB  203.5102s  50.3169 MB/s
8         2MB  224.7242s  45.5670 MB/s
8         1MB  354.7242s  28.8675 MB/s
16        64MB  332.2181s  30.8231 MB/s
16         8MB  261.7113s  39.1271 MB/s
16         4MB  236.5254s  43.2934 MB/s
```
```
Download benchmarks (1GB remote, single file local)
Threads  Chunk Size  Elapsed    Rate
------- …
```

PR: Optimize downloader

---

adlfs/multithread.py

This fixes a regression in the downloader. A 4MB block was determined to be the optimal size.

Change default size of download write block

---

adlfs/core.py
adlfs/transfer.py
tests/test_transfer.py

The temporary file path still uses `/tmp` until #73 is resolved.
Fixes #71

PR: Upload/download 100GB fails without errors

---

adlfs/cli.py
adlfs/core.py
adlfs/lib.py
adlfs/multithread.py
adlfs/transfer.py
adlfs/utils.py
tests/recordings/test_core/test_append.yaml
tests/recordings/test_core/test_chmod.yaml
tests/recordings/test_core/test_delimiters_dash.yaml
tests/recordings/test_core/test_delimiters_newline.yaml
tests/recordings/test_core/test_write_blocks.yaml
tests/test_transfer.py

The main purpose of this PR was to add the necessary file/chunk metadata to make it easier for testing, monitoring progress, and verifying the completed files/chunks. I also refactored how we update the file/chunk statuses while in progress (we use callbacks now instead of polling).
This will allow use to add pre- and post-checks after every chunk transfer.
Fixes #66.

PR: Metadata improvements

---

adlfs/multithread.py
adlfs/transfer.py
tests/benchmarks.py

As retry logic is handled in `adlfs.core`, we no longer need the explicit retry logic in the threads.
I added exception handling when transferring chunks or merging. I also improved resistance to errors when benchmarking. This will help with debugging.

PR: Simplify exception handling

---

adlfs/lib.py

We now log the request and response when debug is enabled. Also, I added the 'x-ms-client-request-id' header to the request.
Fixes #47.

PR: Trace logging

---

azure/datalake/store/multithread.py

This results in the concat operation taking substantially less time.

Optimize the merge call to remove the temp dir

---

azure/datalake/store/cli.py
azure/datalake/store/core.py
azure/datalake/store/lib.py
azure/datalake/store/transfer.py
tests/benchmarks.py
tests/test_core.py
tests/test_transfer.py

When debugging, the request and response is grouped respectively into a single message for clearer logs. We also now record Azure operation and parameters.
When an exception occurs, we record the response and body along with the exception. This will happen with all HTTP status codes in the 4xx or 5xx range.
I also removed unused imports and file/chunk metadata.
Fixes #91.

PR: Actionable errors

---

azure/datalake/store/lib.py

This will use the default client id if the following conditions are met:
1. The user does not add one to an environment variable
2. The user does not pass one in during lib.auth().

Update to use the default client_id (issue #96)

---

azure/datalake/store/lib.py

by modifying the global self.head property within the Call function, there is no guarantee that it is not modified again by a different thread before the current thread finishes logging and execution. assigning to a local variable and using that should alleviate this issue.

Fix headers to ensure unique IDs

---

azure/datalake/store/exceptions.py
azure/datalake/store/lib.py
tests/test_lib.py

I moved the catch-all DatalakeRESTException with the other exceptions.
I also specifically handle bad offset exceptions at the lowest level so it can handled as needed higher up.
Needed for #85.

PR: Add specific exception for bad offset errors

---

azure/datalake/store/core.py
azure/datalake/store/lib.py
azure/datalake/store/multithread.py

When testing bad offset errors, I find a few minor issues:
- explicitly copy headers dictionary (by default Python copies reference)
- clean up exception messages (formatted messages had raw `%s` in string)
- removed one level of indentation from `flush()`
- use `writable()` check instead of comparing against hard-coded set of file modes

PR: Miscellaneous fixes

---

azure/datalake/store/core.py
azure/datalake/store/exceptions.py
azure/datalake/store/lib.py
azure/datalake/store/multithread.py
azure/datalake/store/transfer.py
tests/test_core.py

To address intermittent connection issues for downloads, I added retry logic, but I had to restart the content stream. I also added an exponential backoff to the retry logic.
Edit: switched to linear backoff due to Python 3.3 performance issues

PR: Retry with constant time backoff

---

azure/datalake/store/exceptions.py
azure/datalake/store/lib.py
azure/datalake/store/multithread.py
azure/datalake/store/transfer.py
tests/benchmarks.py

When a thread completes, we check if all bytes in a chunk are transferred. If not, we internally recorded an error, but failed to make it aware to the user. This was the source of the silent error.
To prevent future regressions, I added a final step after transfer that will show all errors to the user. I also added a method to check the success of a transfer: `successful()`. This allows a user to manually check the transfer success.
Fixes #108.

PR: Fix silent errors

---

azure/datalake/store/multithread.py
azure/datalake/store/transfer.py

This means that progress tracking is not captured by default, but it
also means more performant uploads and downloads due to issue:
https://github.com/Azure/azure-data-lake-store-python/issues/142
Once that issue is resolved progress tracking should be supported/on by
default.

Set Verbose to false by default

---

HISTORY.rst
MANIFEST.in
azure/datalake/store/__init__.py
azure/datalake/store/core.py
azure/datalake/store/multithread.py
azure_bdist_wheel.py
setup.cfg
setup.py

These changes enable support for the potential throttling of an upload or download from the server. We have enabled back-off retry logic by default now. In addition, downloads that are being throttled can result in a smaller number of bytes being returned than was requested. This needs to be checked for and the download request needs to be retried until all the expected bytes have been received.

Updates to support throttling management

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/lib.py

Issue:  https://github.com/pyca/pyopenssl/issues/625 causes a
perf issue in our SDK when pyOpenSSL is installed. 
This workaround allows us to ensure that we do not use pyOpenSSL when it is installed until the above mentioned issue is investigated and resolved.

Work around for issue with pyOpenSSL

---

azure/datalake/store/lib.py

Reduction of variable calls for enforcing_no_py_open_ssl() which makes
it easier to read.

Minor code cleanup change.

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/multithread.py
azure/datalake/store/transfer.py
tests/test_multithread.py

This change puts files that are being downloaded but have not yet finished into an "in progress" state, finally renaming them at the end. This ensures that if there is a failure, the user will not see the files as "valid".

Feature request: put files being downloaded into "in progress" state

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/core.py
tests/recordings/test_core/test_ls_empty_with_details.yaml
tests/test_core.py

This fixes a regression when showing details. We should always return an
empty array even if details are asked for, when an ls call has no
children to return.

Fix regression and add a test

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/lib.py
tests/README.md
tests/recordings/test_lib/test_auth_refresh_for_service_principal.yaml
tests/settings.py
tests/test_lib.py

This change addresses issue: https://github.com/Azure/azure-data-lake-store-python/issues/165 and adds a quality of life improvement to automatically refresh service principal credentials when they expire within the client, removing that responsibility from the caller of the SDK.

Add ServicePrincipal token refresh support

---

HISTORY.rst
tests/test_transfer.py

Addendum on 2 previous commits (update HISTORY), remove sleep in test

---

HISTORY.rst
azure/datalake/store/core.py
tests/test_core.py

---
- [ x] The PR has modified HISTORY.rst with an appropriate description of the change and a version increment.
- [x ] The PR has supporting test coverage that confirm the expected behavior and protects against regressions, including necessary recordings.
- [ x] Links to associated bugs, if any, are in the description.

Cache leak

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/core.py
azure/datalake/store/multithread.py
azure/datalake/store/transfer.py
tests/test_multithread.py

---
This is to fix issue #214 and also make sure that empty directories, if they exist are downloaded.
- [] The PR has supporting test coverage that confirm the expected behavior and protects against regressions, including necessary recordings.
I am not sure about recordings here.

Fix to maintain directory structure for single files and empty dirs

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/multithread.py
tests/test_multithread.py

---
* Fixed bug in single file check when rpath has root folder in it for #214 
* Added Python2 exception compatibility based on #227

Fixed bug in single file check when rpath has root folder

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/core.py
tests/test_core.py

---
Adds recovery from DatalakeBadOffsetException, in cases where data write succeeded in the backend, but sdk didn't get the correct response back.

Bad offset recovery fix

---

.travis.yml
HISTORY.rst
azure/datalake/store/__init__.py

---
Changing the order of distributions parameter. With the previous order i.e sdist first, the whl package created doesn't have azure-nspkg as dependency. 
This causes imports to fail for Python 2.7(#236 ) due to different import behavior in Python 2 vs 3. 
- [] The PR has supporting test coverage that confirm the expected behavior and protects against regressions, including necessary recordings.
NA

Fix for issue #236

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/multithread.py
tests/test_core.py
tests/test_multithread.py

---
* Fixed test bug #235 
* Fixed empty folder upload bug #230 
* Fixed ADL Downloader block size bug where the request to download was not getting split into blocksize divisions.

Various bug fixes.

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/multithread.py
tests/test_core.py
tests/test_multithread.py

* Fix for test case failure by adding randomized file path  #235 
* Fix for empty folder upload issue #230
* Fix chunked downloader to make block size requests
---

Various bug fixes. (#243)

---

azure/datalake/store/core.py
azure/datalake/store/lib.py
azure/datalake/store/retry.py
setup.py
tests/settings.py
tests/test_mock.py

---
Add retry for auth method in lib.py that gets the token for the first time. Also moved check_token under the retry code block in call method so we don't fail a call because of transient issues in token refresh.
Will be done when merge to master
- [] Links to associated bugs, if any, are in the description.
NA

Retry for authentication(getting tokens)

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/lib.py
azure/datalake/store/retry.py

---
Reverts some changes introduced in 0.0.35. tokens are used across azure ecosystem, and to maintain compatibility, we can not modify that DataLakeCredentials class substantially. Added retries only for check_token(). While this is more coarse grained, this will work with tokens obtained from other azure libraries. #255

Fix for external token not having retry options

---

azure/datalake/store/lib.py

---
Triggers early download of response.content so it can be retried in case a connection drops in middle of reading the stream.
Will be done when merge to master.
NA.
NA

Fix for Chunked Decoding exception thrown while reading response.content

---

azure/datalake/store/multithread.py
tests/recordings/test_multithread/test_download_glob_single_file.yaml
tests/test_multithread.py

---
There is a bug in the code where when we encounter len(rfiles)==1, we try to check whether the rpath contained a dir or a file. When rpath is a glob i.e contains a * or ? this check fails as it tries to query the path as is. That is the info on paths like "/root/a/*/b.txt" fails and raises an exception.
Will be done when merge to master

Fix glob single file bug

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/core.py
azure/datalake/store/lib.py

---
Add continuation token to LISTSTATUS api call
Update api-version to 2018-09-01

Add continuation token to list status api

---

azure/datalake/store/core.py
tests/test_core.py

---
flush was returning early if buffer is empty, even when called with force flag. Fixed.
Made sure that the delimiter test doesn't require on adls internal behavior.
opening a file required 3 separate calls to getFileStatus. Now it takes only one call.
will do when merge to master.

Fix flush and open

---

.travis.yml
HISTORY.rst
Readme.md
azure/datalake/store/__init__.py
azure/datalake/store/core.py

---
Write was copying all data given to it. This can cause memory issues if the data to be written is large enough. Buffered the writes to block size.

Buffer writes to block size 

---

azure/datalake/store/retry.py

Add positional arguments to `NoRetryPolicy.should_retry`, so that an exception [here](https://github.com/Azure/azure-data-lake-store-python/blob/master/azure/datalake/store/lib.py#L429) will yield the correct behaviour.
Otherwise, the error will be `TypeError: should_retry() takes 1 positional argument but 4 were given` when `NoRetryPolicy` is used.
---

fix: Add positional arguments to NoRetryPolicy.should_retry

---

docs/source/conf.py

conf.py imports the version from the local module, so it needs to have the
directory in the python path, otherwise it fails with:
$ sphinx-apidoc -f -e -o docs/api azure/datalake/store
Creating file docs/api/store.core.rst.
Creating file docs/api/store.enums.rst.
Creating file docs/api/store.exceptions.rst.
Creating file docs/api/store.lib.rst.
Creating file docs/api/store.multiprocessor.rst.
Creating file docs/api/store.multithread.rst.
Creating file docs/api/store.retry.rst.
Creating file docs/api/store.transfer.rst.
Creating file docs/api/store.utils.rst.
Creating file docs/api/store.rst.
Creating file docs/api/modules.rst.
$ make -C docs man
make: Entering directory '/home/bluca/git/azure-data-lake-store-python/docs'
sphinx-build -b man -d build/doctrees   source build/man
Running …

Add source root dir to python path in docs/source/conf.py

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/retry.py

---
Fix adal error when exception doesn't return correct response. ADAL was returning exception where e.error_response was probably an empty string. this happens when ADAL failed to parse the exception. Since this is a GET operation, we can still retry this.

Fix error in retry when adal exception doesn't return response with json

---

HISTORY.rst
azure/datalake/store/core.py

azure/datalake/store/core.py has two logger lines that log with verbosity "info", which should be "debug" (I think). The log of my app is filled with "closing stream" messages for each and every file I open. I feel it does not make sense for a library to log routine tasks with such verbosity.

changed logger verbosity to debug

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/lib.py

urllib3 is now deprecating pyopenssl and emits a warning whenever the module is accessed. Since this pacakge’s access of the module is already optional, and falls back gracefully when the module does not exist, the warning can simply be suppressed.
See: https://github.com/urllib3/urllib3/issues/2680
---

Suppress urllib3 pyopenssl deprecation warning

---

tests/test_core.py

---
There are some tests which calls API which are not supported over symlink currently and are expected to fail such as concat. With this PR, we are skipping those tests, so we have cleaner test reports.

Skip tests which are expected to fail over symlink

---

HISTORY.rst
azure/datalake/store/multithread.py
azure/datalake/store/transfer.py
tests/test_multithread.py

---
Earlier, upload of large files is done in chunks. Multiple chunks get uploaded to temporary destination file and at last, all the temporary files get merged using concat operation.
With this change, we have removed merge operation and upload of large files will be done in single chunk directly to remote destination file.

Remove concat operation from multi-part upload
