adlfs/core.py

Update docs on FileSystem

---

adlfs/cli.py
tests/recordings/test_cli/test_chgrp.yaml
tests/recordings/test_cli/test_chown.yaml
tests/recordings/test_core/test_chown.yaml
tests/test_cli.py
tests/test_core.py

PR: SetOwner tests

---

adlfs/multithread.py
adlfs/transfer.py
tests/test_multithread.py
tests/test_transfer.py

PR: Move temporary files under destination path

---

adlfs/multithread.py
adlfs/transfer.py
tests/test_transfer.py

PR: Clean shutdown

---

adlfs/multithread.py
adlfs/transfer.py
tests/recordings/test_multithread/test_download_glob.yaml
tests/recordings/test_multithread/test_download_overwrite.yaml
tests/recordings/test_multithread/test_upload_glob.yaml
tests/test_cli.py
tests/test_multithread.py

(controlled using verbose= flag in constructor)

Produce textual feedback on transfer process

---

azure/datalake/store/core.py
azure/datalake/store/lib.py
azure/datalake/store/multithread.py
azure/datalake/store/transfer.py
tests/benchmarks.py
tests/recordings/test_cli/test_cat.yaml
tests/recordings/test_cli/test_get.yaml
tests/recordings/test_multithread/test_download_single_file.yaml
tests/recordings/test_multithread/test_download_single_to_dir.yaml

This creates a fast path for downloads. I removed explicit buffering and I now stream chunks as available.

PR: Unbuffered and streaming download

---

azure/datalake/store/cli.py
azure/datalake/store/core.py
tests/recordings/test_cli/test_df.yaml
tests/recordings/test_core/test_df.yaml
tests/test_core.py

This will allow us to get the content summary for a particular path. This prevents the test recordings from taking too long if the account has a large amount of data.

PR: Add optional path to df

---

azure/datalake/store/lib.py
tests/benchmarks.py

In addition to thread-local sessions, I also improved the benchmarking CLI so that we could toggle log messages, verification, checksums, or iterations. It also outputs benchmarking statistics.
Fixes #112

PR: Thread-local sessions

---

azure/datalake/store/multithread.py

PR: Fix type error

---

.travis.yml
README.rst

Adds coveralls support for Travis CI and badge to README.

Add coveralls for Travis CI.

---

.travis.yml
appveyor.yml
azure/datalake/store/__init__.py

Update version and enable pypi deployment.
update appveyor to include python3.6

Enable auto pypi deployment

---

.travis.yml
README.rst
appveyor.yml
azure/datalake/store/__init__.py

Updating version in dev and getting in sync with master.

Update version and get in sync with master

---

azure/datalake/store/utils.py

Logger is not used in this file anywhere, so it should not be imported.

Missed one cleanup change

---

HISTORY.rst
README.rst
setup.py

These were changes made to make the pypi package renderer happy. These
should be persisted across both branches.

Merging back the changes from master into dev

---

MANIFEST.in
azure_bdist_wheel.py
setup.cfg
setup.py

Hi @begoldsm
This is the new packaging system I told you about.
TL;DR; Handling namespace package like `azure` is over complicated in Python. This fixes that.
Details:
The "declare_namespace" clause you have in your `azure/__init__.py` is time consuming. So if we can, we need to avoid it. However, it's interesting in some scenarios (like testing) to have it, so we want it on Github, but not on the client machine.
Moreover, there is two packaging systems in Python: setuptools and wheel. They are totally different and does not work the same way. It's why we publish on PyPI a whl file (pip and wheel) and a zip file,
called a sdist (setuptools).
Usually, put the same content on both files is fine. But in some situation, like namespace package, it's not the more optimized way. So this PR will …

New packaging system

---

.travis.yml

According to doc:
https://docs.travis-ci.com/user/deployment/pypi/

Move distributions to the correct place

---

.gitignore
HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/multithread.py

This is issue:
https://github.com/Azure/azure-data-lake-store-python/issues/169
---

Fix a bug with over collapsing paths

---

HISTORY.rst
azure/datalake/store/transfer.py

File state incorrectly marked as "errored" if contains chunks is "pending" state #182

---

.gitignore

added .idea directory to gitignore

---

HISTORY.rst
azure/datalake/store/__init__.py

---
Updating the package version to publish the progress controller
callback.

Publish package with progress controller callback

---

.travis.yml
azure/datalake/store/core.py
azure/datalake/store/enums.py
azure/datalake/store/lib.py
tests/conftest.py
tests/fake_settings.py
tests/settings.py
tests/test_cli.py
tests/test_core.py

add sync flag, session id in rest calls during read/write

---

HISTORY.rst
azure/datalake/store/transfer.py
tests/test_transfer.py

Fixed Multi chunk transfer hangs as merging chunks fails (#187)

---

GUIDANCE.md
README.rst

* Added a Tests section in the README to point to the tests folder
* Added a link to GUIDANCE.md for more exposure on how to contribute to
the project
* Added a section for Code of Conduct
* Made other minor additions/revisions
---

Revising README.rst

---

README.rst
azure/datalake/store/lib.py

Update endpoint adn fix readme format

---

azure/datalake/store/lib.py
tests/settings.py

change management endpoint

---

azure/datalake/store/__init__.py

---
- [ x] The PR has modified HISTORY.rst with an appropriate description of the change and a version increment.
- [ x] The PR has supporting test coverage that confirm the expected behavior and protects against regressions, including necessary recordings.
- [ x] Links to associated bugs, if any, are in the description.

updating the version number for release

---

HISTORY.rst
azure-data-lake-store-python.pyproj
azure/datalake/store/__init__.py
azure/datalake/store/core.py
azure/datalake/store/lib.py
azure/datalake/store/multithread.py
azure/datalake/store/retry.py
dev_requirements.txt
setup.py
tests/test_mock.py

Retry policy

---

HISTORY.rst
README.rst
azure/datalake/store/multithread.py
tests/README.md

---
Fix for #223 i.e. Readme cleanup and a small bug introduced in #224 due to not importing errno.

Readme cleanup and a minor bug fix

---

HISTORY.rst
azure/datalake/store/__init__.py

---
This is to fix the typo in previous pull request with regards to date in History.rst.
- [] The PR has supporting test coverage that confirm the expected behavior and protects against regressions, including necessary recordings.
NA
- [] Links to associated bugs, if any, are in the description.
NA

Fix history.rst and update version number

---

azure/datalake/store/core.py
azure/datalake/store/lib.py
tests/test_core.py

---
Added `ls_batch` method for listing files in directory batch by batch, to handle large files in directory

add list files by batches

---

azure/datalake/store/core.py
azure/datalake/store/lib.py
tests/test_core.py

---
This fixes #245 , which failed due MSCONCAT not handling '+' in the filenames. Modified concat function to send file list in json so '+' isn't mangled due to HTTP transformation.
Also updated api-version to 2018-05-01
- [] The PR has modified HISTORY.rst with an appropriate description of the change and a version increment.
Will add when merging to master

Concat should send source files in json

---

azure/datalake/store/core.py
azure/datalake/store/multithread.py

---
Updated dostrings for public methods
NA
NA
Fixes #263

Updated docstrings

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/core.py
azure/datalake/store/lib.py
tests/README.md

Update README.md for tests

---

Readme.md

This updates the `README.md` to make sure readers know that this library supports ADLS Gen1, and where to turn for Gen2 support.

Updated README.md to reflect the support for ADLS Gen1 by this library.

---

HISTORY.rst
azure/datalake/store/__init__.py
azure/datalake/store/core.py

---
Release 0.0.51
Add more logging for zero byte reads.

Release 0.0.51. Add more logging for zero byte reads

---

tests/settings.py
tests/test_multithread.py
tests/testing.py

To automate Python SDK Test Run
